//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterv2
{
    using FitnessCenterv2.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

    public partial class GuestList
    {

        public int GuestID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        [Required, Display(Name = "Guest First")]
        public string GuestFirstName { get; set; }
        [Required, Display(Name = "Guest Last")]
        public string GuestLastName { get; set; }
        [Required, 
        Display(Name = "Date"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true),
        CustomDateRange]
        public Nullable<System.DateTime> Date { get; set; }

        public virtual Customer Customer { get; set; }
    }
}
