//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterv2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainer
    {
        public Trainer()
        {
            this.TrainerCustomerATables = new HashSet<TrainerCustomerATable>();
            this.TrainerSchedules = new HashSet<TrainerSchedule>();
            this.WorkoutPrograms = new HashSet<WorkoutProgram>();
        }

        public int ID { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "First Name")]
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        [Required, EmailAddress]
        public string EMail { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        [Required, Display(Name = "Salary"), Range(0, double.MaxValue), DataType(DataType.Currency)]
        public Nullable<decimal> Salary { get; set; }
        [Required, DataType(DataType.Password)]
        public string Password { get; set; }

        public virtual ICollection<TrainerCustomerATable> TrainerCustomerATables { get; set; }
        public virtual ICollection<TrainerSchedule> TrainerSchedules { get; set; }
        public virtual ICollection<WorkoutProgram> WorkoutPrograms { get; set; }
    }
}
