<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutProgram
    {
        public int ID { get; set; }
        public int TrainerID { get; set; }
        public string Schedule { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutProgram
    {
        public int ID { get; set; }
        public int TrainerID { get; set; }
        public int CustomerID { get; set; }
        public string Schedule { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
>>>>>>> master
